# Site settings
title: LocalGreen
email: michael@localgreen.com.au
description: "Bringing you local produce since 2014"
baseurl: ""
url: "http://localgreen.com.au"

# Build settings
markdown: kramdown
permalink: pretty
